name       : icedtea-web
version    : 1.6.2
release    : 1
source     :
    - http://icedtea.wildebeest.org/download/source/icedtea-web-1.6.2.tar.gz : ce67034096d6b960e2b6cfb5c41a7bd6b30eb2ec7f13bf3ecdb477ff6ce69300
license    : GPL-2.0 
component  : programming.java
summary    : The IcedTea-Web project provides a Free Software web browser plugin running applets written in the Java programming language and an implementation of Java Web Start
description: |
    The IcedTea-Web project provides a Free Software web browser plugin running applets written in the Java programming language and an implementation of Java Web Start, originally based on the NetX project.
builddeps  :
    - pkgconfig(x11)
    - openjdk-8
rundeps    :
    - openjdk-8
setup      : |
    javadir=%libdir%/openjdk-8
    %configure --disable-plugin --with-jdk-home=$javadir --with-jre-home=$javadir/jre/
build      : |
    %make
install    : |
    %make_install
