name       : icedtea-web
version    : 1.8.8
release    : 5
source     :
    - https://github.com/AdoptOpenJDK/IcedTea-Web/archive/refs/tags/icedtea-web-1.8.8.tar.gz : f4203a605a3c9c50acdcc6eef4a366b9fdd36d95edcd76bcbfede01107cb5fe6
license    : GPL-2.0-or-later
component  : programming.java
summary    : IcedTeaWeb is an open source implementation of JSR-56 that is better known as Java Web Start
description: |
    The IcedTea-Web project provides a Free Software web browser plugin running applets written in the Java programming language and an implementation of Java Web Start, originally based on the NetX project.
networking : yes
builddeps  :
    - cargo
    - openjdk-8
rundeps    :
    - openjdk-17
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-8
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    %autogen --disable-native-plugin \
        --with-itw-libs=DISTRIBUTION \
        --with-jdk-home=$JAVA_HOME \
        --with-jre-home=$JAVA_HOME
build      : |
    %make
install    : |
    %make_install

    install -Dm 644 *.desktop -t $installdir/usr/share/applications

    rm -rf $installdir/usr/lib64
