name       : icedtea-web
version    : '1.8'
release    : 3
source     :
    - http://icedtea.wildebeest.org/download/source/icedtea-web-1.8.tar.gz : f0ecea7c7edc4906d5dc963df939624b6895da9605f7350057e20b76d30ffd15
license    : GPL-2.0-or-later
component  : programming.java
summary    : The IcedTea-Web project provides a Free Software web browser plugin running applets written in the Java programming language and an implementation of Java Web Start
description: |
    The IcedTea-Web project provides a Free Software web browser plugin running applets written in the Java programming language and an implementation of Java Web Start, originally based on the NetX project.
networking : yes
builddeps  :
    - cargo
    - openjdk-8
rundeps    :
    - openjdk-8
setup      : |
    javadir=%libdir%/openjdk-8
    %configure --disable-native-plugin\
        --with-itw-libs=DISTRIBUTION \
        --with-jdk-home=$javadir \
        --with-jre-home=$javadir/jre
build      : |
    %make
install    : |
    %make_install
